name: main

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - uses: actions/checkout@v4

      # Set up Node.js and Yarn in the CI environment
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: yarn  # Use caching for Yarn

      # Automatically install Yarn (you don't need it locally)
      - name: Install Yarn
        run: npm install --global yarn

      # Install dependencies and generate yarn.lock if missing
      - run: yarn install --frozen-lockfile || yarn install --force

      # Run type-checking, linting, and tests
      - run: npm run type
      - run: npm run lint
      - run: npm run test --ci
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  deploy-ghpages:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - uses: actions/checkout@v4

      # Set up Node.js and Yarn in the CI environment
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: yarn  # Use caching for Yarn

      # Automatically install Yarn (no local Yarn installation needed)
      - name: Install Yarn
        run: npm install --global yarn

      # Install dependencies and generate yarn.lock if needed
      - run: yarn install --frozen-lockfile || yarn install --force

      # Build the project
      - run: npm run build:demo
        env:
          GITHUB_USER_CONTRIBUTION_API_ENDPOINT: https://snk-one.vercel.app/api/github-user-contribution/

      # Deploy to GitHub Pages
      - uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: gh-pages
          build_dir: packages/demo/dist
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN_GH_PAGES }}
